name: release

on:
  release:
    types: [published]

jobs:
  add_tags:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      uses: olegtarasov/get-tag@v1
      id: tagName
    - name: Run latest-tag
      uses: EndBug/latest-tag@v1.3.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
      with:
        python-version: 3.8
    - name: Create new tags
      run: python .github/workflows/create_tags.py "${{ steps.tagName.outputs.tag }}"
